services:
  db:
    image: postgres:15-alpine
    container_name: vfor2lokaverkefni_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: vfor2lokaverkefni
    ports:
      - "5433:5432"          
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: